import type { Task } from '@productivity/shared';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { formatDate } from '@/lib/format';
import { useTaskOccurrences, useUpdateOccurrence } from './hooks';

export function OccurrencesDialog({
  task,
  onOpenChange,
}: {
  task: Task | null;
  onOpenChange: (open: boolean) => void;
}) {
  const { data, isLoading } = useTaskOccurrences(task?.id ?? null);
  const update = useUpdateOccurrence(task?.id ?? '');

  return (
    <Dialog open={!!task} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Occurrences</DialogTitle>
          <DialogDescription>{task?.title}</DialogDescription>
        </DialogHeader>
        <div className="space-y-2">
          {isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
          {!isLoading && data?.length === 0 && (
            <p className="text-sm text-muted-foreground">
              No occurrences yet — they’re generated by the scheduler.
            </p>
          )}
          {data?.map((o) => (
            <div key={o.id} className="flex items-center justify-between rounded-md border px-3 py-2">
              <div className="flex items-center gap-2">
                <span className="text-sm">{formatDate(o.occurrenceDate)}</span>
                <Badge
                  variant={o.status === 'completed' ? 'success' : o.status === 'skipped' ? 'secondary' : 'warning'}
                >
                  {o.status}
                </Badge>
              </div>
              <div className="flex gap-1">
                <Button
                  size="sm"
                  variant="outline"
                  disabled={update.isPending || o.status === 'completed'}
                  onClick={() => update.mutate({ occId: o.id, input: { status: 'completed' } })}
                >
                  Complete
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  disabled={update.isPending || o.status === 'skipped'}
                  onClick={() => update.mutate({ occId: o.id, input: { status: 'skipped' } })}
                >
                  Skip
                </Button>
              </div>
            </div>
          ))}
        </div>
      </DialogContent>
    </Dialog>
  );
}
